# Docker Compose configuration for NVIDIA GPU support
# This requires nvidia-docker2 or nvidia-container-toolkit to be installed
#
# Usage:
#   docker compose -f compose.yaml -f compose.gpu-nvidia.yaml up

services:
  backend:
    # Use the GPU-optimized Dockerfile
    build:
      dockerfile: Dockerfile.gpu
    
    # NVIDIA GPU configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1  # Use 1 GPU, or "all" for all GPUs
              capabilities: [gpu, compute]
    
    environment:
      # Force Vulkan backend for NVIDIA
      - WGPU_BACKEND=VULKAN
      # Optional: Enable NVIDIA optimizations
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
